### ISSUE TITLE
SortFilterModel

### ISSUE THREAD

**Issue by plfiorini** [qmlos/fluid#23]
Add QML implementation of QSortFilterProxyModel

**Comment by oKcerG** [comment]
Hi, I'm writing a new version (cleaner, more features) of my https://github.com/oKcerG/SortFilterProxyModel library.
Maybe that's something you'd like to use instead of recreating yours.

**Comment by plfiorini** [comment]
Nice @oKcerG. I haven't actually looked at the code yet, but from the API doc it seems to have all we need, except maybe a callback to make a javascript filter.

Thanks for pointing to the class.

**Comment by oKcerG** [comment]
@plfiorini There's a callback to make a javascript filter: `filterExpression`.
May I ask you what's your usecase for such feature ?

**Comment by plfiorini** [comment]
@oKcerG for more complex expression that involve several fields at once
