### ISSUE TITLE
Standardize spacing and margins

### ISSUE THREAD

**Issue by plfiorini** [qmlos/fluid#3]
@iBeliever What about adding a bunch of properties to FluidStyle for standard spacing and margins following the Material guidelines?

**Comment by plfiorini** [comment]
Though I don't understand weather the Material guidelines have standard spacing and margins.

**Comment by iBeliever** [comment]
I'll have to go through the MD guidelines, but I think standard units would be multiples of 8: 8/16/32, and then the grid unit from Device.

**Comment by plfiorini** [comment]
I was a bit confused because when speaking of grids the guidelines says to use different units, in fact all examples seem multiples of 8 but I can't figure out if there's some rule.
On the other hand dialog boxes margins and padding seem standard, I might code those in FluidStyle.
