### ISSUE TITLE
Import components into Fluid.Material

### ISSUE THREAD

**Issue by plfiorini** [qmlos/fluid#9]
List of components that we might want to import:

- [x] https://github.com/papyros/qml-material/blob/develop/src/components/Wave.qml
- [ ] https://github.com/papyros/qml-material/blob/develop/src/components/ActionButton.qml
- [x] Perhaps https://github.com/papyros/qml-material/blob/develop/src/components/Card.qml
- [x] Maybe https://github.com/papyros/qml-material/blob/develop/src/components/ProgressCircle.qml
- [x] https://github.com/papyros/qml-material/blob/develop/src/components/Snackbar.qml
- [x] https://github.com/papyros/qml-material/blob/develop/src/core/View.qml

**Comment by iBeliever** [comment]
Card will need to be replaced with a component more following what Material Design calls a card (with titles, actions, content, etc). Right now Pane in Controls 2 is the equivalent to Card. Instead of View, we can just bring in ElevationEffect from QuickPaper. It's actually been upstreamed to Controls 2, but it isn't publicly accessible.

**Comment by iBeliever** [comment]
ProgressCircle is replaced with BusyIndicator in Controls 2. (though the animation for BusyIndicator feels a bit faster than the spec shows).

**Comment by plfiorini** [comment]
BusyIndicator looks a lot like ProgressCircle but it doesn't show the percentage.
Now that I think this through a progress circle is available on a lot of visual languages: I've seen it in SailfishOS and Windows 10, so it's not Material specific and should be implemented in Fluid.Controls

**Comment by plfiorini** [comment]
Probably Card could be in Fluid.Controls (with the titles, actions, content, etc. properties) and styled with +material as well and derive from Pane, while ElevationEffect seems Fluid.Material related

**Comment by plfiorini** [comment]
Self-assigning, I want to close this issue today or tomorrow.

**Comment by plfiorini** [comment]
Ok let's use BusyIndicator instead of ProgressCircle for now.
